### ISSUE TITLE
Blockquote Styling Bug

### ISSUE THREAD

**Issue by marzzuki** [ndr053/notion-rtl#9]
Hi @ndr053, @NimaKaviyani, @Adam-Saeed,

First, I’d like to thank you for creating such an amazing Notion RTL style. It has made a significant positive impact on my workflow, and I really appreciate the effort you’ve put into this project!

While using the extension, I noticed a small issue with blockquotes:

- **Issue:** Blockquote styling seems broken as it displays two borders instead of one, and the padding appears inconsistent with the rest of the design.

![image](https://github.com/user-attachments/assets/35f0c7b4-5e12-446f-a5f4-6c9b87909c75)

I’m currently working on fixing this and will be submitting a PR shortly to address the issue. I hope my contribution helps improve the style even further!

Thank you again for this wonderful style. Looking forward to collaborating with you

Best regards,
Mustafa

**Comment by ndr053** [comment]
Hi Mustafa,
Thank you for your kind words and for sharing your feedback—it truly means a lot to us! We're thrilled to hear that the RTL style has positively impacted your workflow. We appreciate you bringing the blockquote styling issue to our attention. 
I will check your pull request soon.
